# Generated by Django 3.1.6 on 2021-04-02 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatGoesIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colour', models.CharField(choices=[('W', 'White'), ('B', 'Black'), ('R', 'Red'), ('O', 'Orange'), ('Y', 'Yellow'), ('G', 'Green'), ('B', 'Blue'), ('I', 'Indigo'), ('V', 'Violet')], default='R', max_length=1)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.collector')),
            ],
        ),
    ]
