# Generated by Django 3.1.6 on 2021-04-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_whatgoesin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatgoesin',
            name='colour',
            field=models.CharField(choices=[('0', 'White'), ('1', 'Black'), ('2', 'Red'), ('3', 'Orange'), ('4', 'Yellow'), ('5', 'Green'), ('6', 'Blue'), ('7', 'Indigo'), ('8', 'Violet')], default='2', max_length=1),
        ),
    ]
