# Generated by Django 3.1.6 on 2021-04-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210402_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common_Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='collector',
            name='common_feature',
            field=models.ManyToManyField(to='main_app.Common_Feature'),
        ),
    ]
